from .line import *
from .point import *
from .shape import *
from .rectangle import *
from .square import *
from .triangle import *
from .equilateral import *
from .trirectangle import *
from .isosceles import *
from .scalene import *